#!/usr/bin/env bash
# ai-symbiote setup entrypoint.
#
# Author: JunyoungJung
# Date: 2026-04-15

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../../../hooks/scripts/lib/common.sh"

PROJECT_ROOT="${SETUP_PROJECT_ROOT:-}"
STATE_DIR="${SETUP_STATE_DIR:-}"
OPTIONAL_ITEM="${SETUP_OPTIONAL_ITEM:-}"
STORE_MODE="${SETUP_STORE_MODE:-guided}"
PROJECT_AGENT_CONFIG="${SETUP_PROJECT_AGENT_CONFIG:-false}"
APPROVED="false"

usage() {
  echo "Usage: begin-setup.sh [--project-root PATH] [--state-dir PATH] [--optional-item TEXT] [--store-mode fast|guided|dry-run] [--project-agent-config] [--approve]" >&2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --project-root)
      PROJECT_ROOT="${2:-}"
      shift 2
      ;;
    --state-dir)
      STATE_DIR="${2:-}"
      shift 2
      ;;
    --optional-item)
      OPTIONAL_ITEM="${2:-}"
      shift 2
      ;;
    --store-mode)
      STORE_MODE="${2:-}"
      shift 2
      ;;
    --project-agent-config)
      PROJECT_AGENT_CONFIG="true"
      shift
      ;;
    --approve)
      APPROVED="true"
      shift
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

if [ -z "$PROJECT_ROOT" ]; then
  PROJECT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
fi

if [ -z "$STATE_DIR" ]; then
  STATE_DIR=$(cd "$PROJECT_ROOT" && get_state_dir)
fi

print_plan() {
  SETUP_PLAN_OPTIONAL_ITEM="$OPTIONAL_ITEM" \
  bash "$SCRIPT_DIR/render-setup-plan.sh" \
    --project-root "$PROJECT_ROOT" \
    --state-dir "$STATE_DIR"
}

ensure_project_agent_config() {
  local claude_dir codex_dir gitignore
  claude_dir="$PROJECT_ROOT/.claude"
  codex_dir="$PROJECT_ROOT/.codex"
  gitignore="$PROJECT_ROOT/.gitignore"

  mkdir -p "$claude_dir" "$codex_dir"

  if [ ! -f "$claude_dir/settings.json" ]; then
    cat > "$claude_dir/settings.json" <<'EOF'
{
  "permissions": {
    "allow": [
      "Bash(*)",
      "Read(*)",
      "Write(*)",
      "Edit(*)",
      "Glob(*)",
      "Grep(*)",
      "WebFetch(*)",
      "WebSearch(*)",
      "Agent(*)",
      "Skill(*)",
      "NotebookEdit(*)"
    ],
    "deny": []
  }
}
EOF
    echo "[Setup] created .claude/settings.json"
  fi

  if [ ! -f "$codex_dir/config.toml" ]; then
    cat > "$codex_dir/config.toml" <<'EOF'
# Codex project config (auto-generated by ai-symbiote setup)
model = "gpt-5.4"
approval_mode = "suggest"
EOF
    echo "[Setup] created .codex/config.toml"
  fi

  [ -f "$gitignore" ] || touch "$gitignore"
  if ! grep -qxF '# AI agent project config (auto-generated by ai-symbiote setup)' "$gitignore" 2>/dev/null; then
    {
      [ -s "$gitignore" ] && printf '\n'
      echo '# AI agent project config (auto-generated by ai-symbiote setup)'
    } >> "$gitignore"
  fi
  grep -qxF '.claude/' "$gitignore" 2>/dev/null || echo '.claude/' >> "$gitignore"
  grep -qxF '.codex/' "$gitignore" 2>/dev/null || echo '.codex/' >> "$gitignore"
}

prepare_state_root() {
  mkdir -p "$STATE_DIR/usage-data/skills"
  mkdir -p "$STATE_DIR/usage-data/commands"
  mkdir -p "$STATE_DIR/state"
  mkdir -p "$STATE_DIR/taskmaster"
  mkdir -p "$STATE_DIR/ralph"
  mkdir -p "$STATE_DIR/messenger"
  date -u +%Y-%m-%dT%H:%M:%SZ > "$STATE_DIR/usage-data/.tracked-since"
  echo "[Setup] prepared state directory: $STATE_DIR"
}

execute_setup() {
  echo "[Setup] Approval received. Executing setup..."
  prepare_state_root
  if [ "$PROJECT_AGENT_CONFIG" = "true" ]; then
    ensure_project_agent_config
  else
    echo "[Setup] skipped project agent config (.claude/, .codex/, .gitignore). Re-run with --project-agent-config to create it."
  fi
  bash "$SCRIPT_DIR/run-store-setup.sh" \
    --state-dir "$STATE_DIR" \
    --project-root "$PROJECT_ROOT" \
    --mode "$STORE_MODE"
  if [ -f "$STATE_DIR/manifest.json" ]; then
    bash "$SCRIPT_DIR/manifest-defaults.sh" --manifest "$STATE_DIR/manifest.json" >/dev/null
  fi
  echo "[Setup] setup execution complete."
}

if [ "$APPROVED" != "true" ]; then
  print_plan
  echo ""
  echo "[Setup] Re-run with --approve to execute this plan."
  exit 0
fi

execute_setup
